# Generated by Django 3.2.6 on 2021-10-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_data',
        ),
    ]
