# Generated by Django 3.2.6 on 2021-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_event_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_data',
            field=models.TextField(blank=True),
        ),
    ]
